services:
  nod1:
    build: .
    container_name: nod1
    environment:
      - CONFIG_FILE=config_nod1.json
    ports:
      - "8804:8804"
    stdin_open: true
    tty: true

  nod2:
    build: .
    container_name: nod2
    environment:
      - CONFIG_FILE=config_nod2.json
    ports:
      - "8808:8808"
    stdin_open: true
    tty: true

  nod3:
    build: .
    container_name: nod3
    environment:
      - CONFIG_FILE=config_nod3.json
    ports:
      - "8814:8814"
    stdin_open: true
    tty: true
